global:
  scrape_interval: 15s # Set the interval at which Prometheus will scrape the targets

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:9000']
    

  - job_name: 'frontend'
    static_configs:
      - targets: ['metrics-server:3002']

  - job_name: 'mariadb'
    static_configs:
      - targets: ['mysqld_exporter:9104']
